### ISSUE TITLE
Release script is slightly broken

### ISSUE THREAD

**Issue by zeitlinger** [zalando/opentracing-toolbox#515]
# Version Jump

1. Version was `3.0.0-RC.3`
2. I ran `./release.sh major` - which created `4.0.0` - which was unexpected.

# Push release branch

the release script aborted with 

```
fatal: The current branch release/4.0.0 has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin release/4.0.0
```

which I fixed with 

```
Index: release.sh
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/release.sh b/release.sh
--- a/release.sh	(revision Staged)
+++ b/release.sh	(date 1613055669405)
@@ -17,7 +17,7 @@
 ./mvnw versions:set -D newVersion=${next}-SNAPSHOT
 git commit -am "Development ${next}-SNAPSHOT"
 
-git push
+git push --set-upstream origin release/${release}
 git push --tags
 
 git checkout main
```

This worked but raises the question why the release branch should be pushed at all. The was no previous release branch.

**Comment by zeitlinger** [comment]
@whiskeysierra can you help?

**Comment by whiskeysierra** [comment]
> I ran `./release.sh major` - which created `4.0.0` - which was unexpected.

Are you sure?

```
$ semver 3.0.0-RC.3 -i major --preid RC
3.0.0
```

**Comment by zeitlinger** [comment]
we have a different semver apparently:

```
➜  buildings git:(master) semver 3.0.0-RC.3 -i major --preid RC  
4.0.0

➜  buildings git:(master) semver -h
SemVer 2.1.0

A JavaScript implementation of the http://semver.org/ specification
Copyright Isaac Z. Schlueter

```

**Comment by whiskeysierra** [comment]
The other issue with upstream is most likely due to my git config where have it enabled by default. Matches remote names by name.

**Comment by zeitlinger** [comment]
> The other issue with upstream is most likely due to my git config where have it enabled by default. Matches remote names by name.

why do we need the release branch at all?

**Comment by whiskeysierra** [comment]
To open pull request with the changes
